# Generated by Django 4.1.4 on 2022-12-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_about_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='body',
            new_name='about_body',
        ),
    ]
