# Generated by Django 4.1.4 on 2022-12-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_body_about_about_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
