# Generated by Django 4.1.4 on 2022-12-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_about_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
